"""Generate a starter YAML config for a new dataset.

The config format needs every column name to match the dataframe exactly, and
writing that by hand is exactly the kind of transcription step that produces
silent typos. This module reads the real dataframe once and writes a config
with every column already present, correctly named, and lightly annotated
with a guessed semantic type, so the only work left is filling in
descriptions and synonyms.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import yaml

from mcp_dataframe_qa.datasets import load_dataframe

_IDENTIFIER_HINTS = ("_id", "identifier", "code", "sku")
_CURRENCY_HINTS = ("price", "cost", "revenue", "profit", "sales", "amount", "fee", "fare")
_COUNT_HINTS = ("count", "quantity", "qty", "number", "num", "total")


def dataset_slug(data_path: str) -> str:
    """Turn a file path into a short, config-friendly identifier.

    ``~/Downloads/my data (2).csv`` becomes ``my_data_2``. Used both as the
    default dataset id/table name and as the default output filename, so a
    generated config is traceable back to the file it came from.
    """
    stem = Path(data_path).stem
    slug = "".join(ch.lower() if ch.isalnum() else "_" for ch in stem)
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_") or "dataset"


def _infer_semantic_type(column: str, series: pd.Series) -> str | None:
    """Guess a semantic type from the column name and dtype.

    This is deliberately conservative. A wrong guess is worse than no guess,
    since it would mislead the planner instead of just leaving it uninformed.
    Numeric columns with no recognizable name pattern are left blank rather
    than guessed, since "count" versus "currency" versus "measurement" isn't
    reliably inferable from dtype alone.
    """
    lowered = column.lower()
    if lowered == "id" or lowered.endswith(_IDENTIFIER_HINTS) or "identifier" in lowered:
        return "identifier"
    if pd.api.types.is_datetime64_any_dtype(series):
        return "date"
    if any(hint in lowered for hint in _CURRENCY_HINTS):
        return "currency"
    if any(hint in lowered for hint in _COUNT_HINTS):
        return "count"
    if pd.api.types.is_numeric_dtype(series):
        return None
    return "dimension"


def build_starter_config(data_path: str) -> dict:
    """Build the config dict for ``data_path``, ready to serialize as YAML."""
    frame = load_dataframe(data_path)
    slug = dataset_slug(data_path)

    columns: dict[str, dict] = {}
    for column in frame.columns:
        name = str(column)
        columns[name] = {
            "description": "",
            "semantic_type": _infer_semantic_type(name, frame[column]),
            "synonyms": [],
        }

    return {
        "dataset": {
            "id": slug,
            "path": data_path,
            "table_name": slug,
        },
        "limits": {
            "max_rows_returned": 100,
            "max_execution_ms": 3000,
            "max_cell_chars": 500,
            "max_preview_rows": 20,
        },
        "columns": columns,
    }


def write_starter_config(data_path: str, out_path: str) -> Path:
    """Write a starter config for ``data_path`` to ``out_path`` and return it."""
    config = build_starter_config(data_path)
    out = Path(out_path)
    with out.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by --init-config. Descriptions and synonyms are\n"
            "# blank on purpose, fill them in for better answers, then run:\n"
            f"#   uv run mcp-dataframe-chat --config {out.name}\n"
        )
        yaml.safe_dump(
            config, handle, sort_keys=False, default_flow_style=False, allow_unicode=True
        )
    return out
